name: Scala/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  small-designs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout essent & firrtl-sig
        uses: actions/checkout@v2
        with:
            submodules: true

      - name: cache SBT deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: build stuff
        run: sbt compile

      - name: run small designs
        run: sbt 'run all'
